- project:
    templates:
      - build-openstack-docs-pti
    check:
      jobs:
        - openstack-tox-linters:
            required-projects:
              - openstack-infra/project-config
    experimental:
      jobs:
        - openstack-tox-validate
    gate:
      jobs:
        - openstack-tox-linters:
            required-projects:
              - openstack-infra/project-config
    post:
      jobs:
        - publish-governance-tc
